param(
    [string]$Release = "Digital 26.12",
    [string]$ProjectKey = "IQE",
    [string]$TierPoolJson,
    [switch]$Execute
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. "$PSScriptRoot\common.ps1"

$reportsPath = Get-RegressionReportsPath
if (-not $TierPoolJson) {
    $TierPoolJson = Join-Path $reportsPath "tier_test_pools.json"
}

if (-not (Test-Path $TierPoolJson)) {
    throw "Tier pool file not found: $TierPoolJson"
}

$pool = Get-Content -Raw -Path $TierPoolJson | ConvertFrom-Json
$results = @()

foreach ($tierName in @("Tier1", "Tier2", "Tier3")) {
    $tests = @($pool.$tierName)
    if ($tests.Count -eq 0) {
        continue
    }

    $testKeys = @($tests | ForEach-Object { $_.key } | Sort-Object -Unique)
    $teName = "PROJ-$($Release.Replace(' ', '_'))-REGRESSION-$tierName"
    $description = "Regression execution for $Release ($tierName). Generated by scripts/regression/create-test-executions.ps1"

    $payload = @{
        projectKey   = $ProjectKey
        testCaseKeys = $testKeys
        name         = $teName
        description  = $description
    }

    if ($Execute) {
        $created = Invoke-exampleMCP -Tool "xray_create_test_execution" -Params $payload
        $teKey = if ($created.key) { $created.key } else { "UNKNOWN" }
        $status = "created"
    }
    else {
        $teKey = "DRY-RUN"
        $status = "planned"
    }

    $results += [pscustomobject]@{
        tier         = $tierName
        te_name      = $teName
        te_key       = $teKey
        status       = $status
        test_count   = $testKeys.Count
        sample_tests = (@($testKeys | Select-Object -First 15) -join "|")
    }
}

$outputPath = Join-Path $reportsPath "test_executions_$($Release.Replace(' ','_')).csv"
$results | Export-Csv -NoTypeInformation -Encoding UTF8 -Path $outputPath

Write-Host "TE planning output exported: $outputPath"
if (-not $Execute) {
    Write-Host "Dry run mode: no test executions were created. Re-run with -Execute to create in Xray."
}
