#!/usr/bin/env python3
"""
Shuriken — Publish test results to Confluence.
Creates/updates a page with pass/fail matrix, screenshots, timings, and build info.

Usage:
  python3 publish-confluence-report.py \
    --results-dir test-results/ \
    --space-key QE \
    --base-url https://your-tenant.atlassian.net/wiki \
    --email user@example.com \
    --api-token XXXX \
    --build-version 4.2.1-rc.3
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

try:
    import requests
except ImportError:
    print("ERROR: 'requests' package required. Run: pip install requests")
    sys.exit(1)


def load_summaries(results_dir: str) -> list:
    """Load all *-summary.json files from the results directory."""
    summaries = []
    results_path = Path(results_dir)
    for f in sorted(results_path.glob("*-summary.json")):
        with open(f) as fh:
            summaries.append(json.load(fh))
    return summaries


def build_confluence_html(summaries: list, build_version: str, pipeline_url: str) -> str:
    """Generate Confluence storage format HTML for the test report."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Resolve app version from summaries if available
    app_ver = ""
    for s in summaries:
        v = s.get("app_version", "")
        if v:
            app_ver = v
            break
    display_version = app_ver or build_version

    # Overall stats
    total = sum(s["total"] for s in summaries)
    passed = sum(s["passed"] for s in summaries)
    failed = sum(s["failed"] for s in summaries)
    errors = sum(s["errors"] for s in summaries)
    duration = sum(s["duration_s"] for s in summaries)
    overall_status = "✅ PASSED" if failed == 0 and errors == 0 else "❌ FAILED"
    status_color = "#00875A" if "PASSED" in overall_status else "#DE350B"

    html = f"""
<ac:structured-macro ac:name="info" ac:schema-version="1">
  <ac:rich-text-body>
    <p><strong>🍽️ Shuriken — Smoke Test Report</strong></p>
    <p>App Version: <strong>{display_version}</strong> | Run: {now} | 
    <a href="{pipeline_url}">GitLab Pipeline</a></p>
  </ac:rich-text-body>
</ac:structured-macro>

<h2>Summary</h2>
<table>
  <tr>
    <th>Status</th>
    <th>Total Tests</th>
    <th>Passed</th>
    <th>Failed</th>
    <th>Duration</th>
  </tr>
  <tr>
    <td><strong style="color:{status_color}">{overall_status}</strong></td>
    <td>{total}</td>
    <td style="color:#00875A"><strong>{passed}</strong></td>
    <td style="color:#DE350B"><strong>{failed + errors}</strong></td>
    <td>{duration:.1f}s</td>
  </tr>
</table>

<h2>Brand Matrix</h2>
<table>
  <tr>
    <th>Brand</th>
    <th>Status</th>
    <th>Total</th>
    <th>Passed</th>
    <th>Failed</th>
    <th>Duration</th>
  </tr>
"""

    for s in summaries:
        brand = s["brand"].upper()
        status_icon = "✅" if s["status"] == "passed" else "❌"
        brand_color = "#00875A" if s["status"] == "passed" else "#DE350B"
        html += f"""  <tr>
    <td><strong>{brand}</strong></td>
    <td style="color:{brand_color}">{status_icon} {s['status'].upper()}</td>
    <td>{s['total']}</td>
    <td>{s['passed']}</td>
    <td>{s['failed'] + s.get('errors', 0)}</td>
    <td>{s['duration_s']:.1f}s</td>
  </tr>
"""

    html += """</table>

<h2>Test Details</h2>
"""

    for s in summaries:
        brand = s["brand"].upper()
        html += f"""<h3>{brand}</h3>
<table>
  <tr><th>Test</th><th>Status</th><th>Duration</th><th>Message</th></tr>
"""
        for t in s.get("tests", []):
            icon = {"passed": "✅", "failed": "❌", "error": "💥", "skipped": "⏭️"}.get(t["status"], "❓")
            msg = (t.get("message") or "")[:200]
            html += f"""  <tr>
    <td>{t['name']}</td>
    <td>{icon} {t['status']}</td>
    <td>{t['duration_s']:.1f}s</td>
    <td><code>{msg}</code></td>
  </tr>
"""
        html += "</table>\n"

    html += f"""
<hr/>
<p><em>Generated by Shuriken — Predictive Lifecycle Assurance &amp; Testing Engine</em></p>
<p><em>Pipeline: <a href="{pipeline_url}">{pipeline_url}</a></em></p>
"""
    return html


def create_or_update_page(
    base_url: str,
    space_key: str,
    title: str,
    content: str,
    email: str,
    api_token: str,
    parent_page_id: str = None,
) -> dict:
    """Create or update a Confluence page."""
    auth = (email, api_token)
    headers = {"Content-Type": "application/json"}

    # Search for existing page with same title
    search_url = f"{base_url}/rest/api/content"
    params = {"title": title, "spaceKey": space_key, "expand": "version"}
    resp = requests.get(search_url, params=params, auth=auth, headers=headers)
    resp.raise_for_status()
    results = resp.json().get("results", [])

    if results:
        # Update existing page
        page = results[0]
        page_id = page["id"]
        version = page["version"]["number"] + 1
        data = {
            "version": {"number": version},
            "title": title,
            "type": "page",
            "body": {"storage": {"value": content, "representation": "storage"}},
        }
        url = f"{base_url}/rest/api/content/{page_id}"
        resp = requests.put(url, json=data, auth=auth, headers=headers)
        resp.raise_for_status()
        page_data = resp.json()
    else:
        # Create new page
        data = {
            "type": "page",
            "title": title,
            "space": {"key": space_key},
            "body": {"storage": {"value": content, "representation": "storage"}},
        }
        if parent_page_id:
            data["ancestors"] = [{"id": parent_page_id}]
        resp = requests.post(search_url, json=data, auth=auth, headers=headers)
        resp.raise_for_status()
        page_data = resp.json()

    page_url = f"{base_url}{page_data['_links']['webui']}"
    return {"id": page_data["id"], "url": page_url, "title": title}


def main():
    parser = argparse.ArgumentParser(description="Publish Shuriken results to Confluence")
    parser.add_argument("--results-dir", required=True)
    parser.add_argument("--screenshots-dir", default="screenshots/")
    parser.add_argument("--space-key", required=True)
    parser.add_argument("--parent-page-id", default=None)
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--email", required=True)
    parser.add_argument("--api-token", required=True)
    parser.add_argument("--build-version", default="unknown")
    parser.add_argument("--pipeline-url", default="")
    parser.add_argument("--output", default="confluence-result.json")
    args = parser.parse_args()

    summaries = load_summaries(args.results_dir)
    if not summaries:
        print("⚠️  No test summaries found. Creating placeholder report.")
        summaries = [
            {
                "brand": "unknown",
                "buildVersion": args.build_version,
                "total": 0, "passed": 0, "failed": 0, "errors": 1, "skipped": 0,
                "duration_s": 0, "status": "error", "tests": [],
            }
        ]

    # Resolve app version from summaries
    app_ver = ""
    for s in summaries:
        v = s.get("app_version", "")
        if v:
            app_ver = v
            break
    display_version = app_ver or args.build_version

    now = datetime.utcnow().strftime("%Y-%m-%d")
    title = f"Shuriken Smoke Report — {display_version} — {now}"

    html = build_confluence_html(summaries, args.build_version, args.pipeline_url)

    result = create_or_update_page(
        base_url=args.base_url,
        space_key=args.space_key,
        title=title,
        content=html,
        email=args.email,
        api_token=args.api_token,
        parent_page_id=args.parent_page_id,
    )

    Path(args.output).write_text(json.dumps(result, indent=2))
    print(f"✅ Confluence report published: {result['url']}")


if __name__ == "__main__":
    main()
