/**
 * TE AI Comment Audit
 *
 * Fetches run comments from one or more Test Executions and flags likely
 * AI-executed runs using comment patterns such as "AI Generated:".
 *
 * Usage:
 *   npx ts-node src/runners/te-ai-comment-audit.ts --tes TE-10094,TE-10093,TE-10092,TE-10091
 */

import * as fs from 'fs';
import * as path from 'path';
import { getXrayConfig, xrayGraphQL, type XrayConfig } from '../../../shared/xray-client';

interface CliArgs {
  tes: string[];
}

interface RunRow {
  te: string;
  runId: string;
  testKey: string;
  summary: string;
  status: string;
  comment: string;
  source: 'comet' | 'ai' | 'maestro' | 'mcp' | 'other' | 'none';
  evidenceCount: number;
  evidenceFiles: string[];
  aiExecuted: boolean;
}

function parseArgs(): CliArgs {
  const args = process.argv.slice(2);
  let tesRaw = '';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--tes') tesRaw = args[++i] || '';
  }

  const tes = tesRaw
    .split(',')
    .map((v) => v.trim().toUpperCase())
    .filter(Boolean);

  if (!tes.length) {
    throw new Error('Missing --tes <comma-separated TE keys>');
  }

  return { tes };
}

function isAIComment(comment: string): boolean {
  const c = (comment || '').toLowerCase();
  if (!c) return false;

  return (
    c.includes('ai generated') ||
    c.includes('ai-generated') ||
    c.includes('generated by ai') ||
    c.includes('executed by ai') ||
    c.includes('executed as guest user')
  );
}

function detectSource(comment: string): RunRow['source'] {
  const c = (comment || '').toLowerCase();
  if (!c) return 'none';
  if (c.includes('comet')) return 'comet';
  if (c.includes('maestro')) return 'maestro';
  if (c.includes('mcp') || c.includes('playwright')) return 'mcp';
  if (isAIComment(comment)) return 'ai';
  if (c.includes('automation') || c.includes('auto-generated') || c.includes('autogenerated')) return 'other';
  return 'none';
}

async function fetchRunsPage(
  xrayConfig: XrayConfig,
  teKey: string,
  start: number,
): Promise<{ total: number; results: any[] }> {
  try {
    const withEvidence = await xrayGraphQL(
      xrayConfig,
      `{
        getTestExecutions(jql: "key = ${teKey}", limit: 1) {
          results {
            testRuns(limit: 100, start: ${start}) {
              total
              results {
                id
                comment
                status { name }
                test {
                  jira(fields: ["key", "summary"])
                }
                evidences {
                  filename
                }
              }
            }
          }
        }
      }`,
    );

    const te = withEvidence.data?.getTestExecutions?.results?.[0];
    if (!te) throw new Error(`TE ${teKey} not found`);
    return {
      total: te.testRuns?.total || 0,
      results: te.testRuns?.results || [],
    };
  } catch (err: any) {
    // Fallback for Xray schemas that do not expose run evidences in this query.
    if (!String(err?.message || '').toLowerCase().includes('evidence')) throw err;

    const withoutEvidence = await xrayGraphQL(
      xrayConfig,
      `{
        getTestExecutions(jql: "key = ${teKey}", limit: 1) {
          results {
            testRuns(limit: 100, start: ${start}) {
              total
              results {
                id
                comment
                status { name }
                test {
                  jira(fields: ["key", "summary"])
                }
              }
            }
          }
        }
      }`,
    );

    const te = withoutEvidence.data?.getTestExecutions?.results?.[0];
    if (!te) throw new Error(`TE ${teKey} not found`);
    return {
      total: te.testRuns?.total || 0,
      results: te.testRuns?.results || [],
    };
  }
}

async function getRunsWithComments(xrayConfig: XrayConfig, teKey: string): Promise<RunRow[]> {
  const rows: RunRow[] = [];
  let start = 0;

  while (true) {
    const pageData = await fetchRunsPage(xrayConfig, teKey, start);
    const page = pageData.results || [];
    for (const run of page) {
      const comment = run.comment || '';
      const evidenceFiles = Array.isArray(run.evidences)
        ? run.evidences.map((e: any) => String(e?.filename || '')).filter(Boolean)
        : [];
      rows.push({
        te: teKey,
        runId: run.id,
        testKey: run.test?.jira?.key || '???',
        summary: run.test?.jira?.summary || '',
        status: run.status?.name || 'TODO',
        comment,
        source: detectSource(comment),
        evidenceCount: evidenceFiles.length,
        evidenceFiles,
        aiExecuted: isAIComment(comment),
      });
    }

    const total = pageData.total || 0;
    start += page.length;
    if (start >= total || page.length === 0) break;
  }

  return rows;
}

function writeReport(rows: RunRow[]): string {
  const reportsDir = path.resolve(__dirname, '..', '..', 'reports');
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

  const out = path.join(reportsDir, `te-ai-comment-audit-${new Date().toISOString().replace(/[:.]/g, '-')}.json`);
  fs.writeFileSync(out, JSON.stringify({ generatedAt: new Date().toISOString(), rows }, null, 2));
  return out;
}

async function main() {
  const cli = parseArgs();
  const xrayConfig = getXrayConfig();
  if (!xrayConfig) throw new Error('Missing Xray credentials');

  const allRows: RunRow[] = [];
  for (const te of cli.tes) {
    const rows = await getRunsWithComments(xrayConfig, te);
    allRows.push(...rows);
  }

  console.log('\nTE AI Comment Audit');
  console.log('═══════════════════════════════════════════════════════');

  for (const te of cli.tes) {
    const rows = allRows.filter((r) => r.te === te);
    const withComments = rows.filter((r) => r.comment && r.comment.trim().length > 0);
    const ai = rows.filter((r) => r.aiExecuted);
    const comet = rows.filter((r) => r.source === 'comet');
    const maestro = rows.filter((r) => r.source === 'maestro');
    const mcp = rows.filter((r) => r.source === 'mcp');
    const evidence = rows.filter((r) => r.evidenceCount > 0);

    console.log(`\n${te}`);
    console.log(`  Total runs:        ${rows.length}`);
    console.log(`  Runs w/ comments:  ${withComments.length}`);
    console.log(`  AI-like comments:  ${ai.length}`);
    console.log(`  Comet comments:    ${comet.length}`);
    console.log(`  Maestro comments:  ${maestro.length}`);
    console.log(`  MCP comments:      ${mcp.length}`);
    console.log(`  Runs w/ evidence:  ${evidence.length}`);

    for (const r of ai) {
      console.log(`  - ${r.testKey} (${r.status})`);
      console.log(`    ${r.comment.substring(0, 180)}`);
    }

    if (comet.length > 0) {
      console.log('  Comet-marked runs:');
      for (const r of comet) {
        console.log(`  - ${r.testKey} (${r.status})`);
        console.log(`    ${r.comment.substring(0, 180)}`);
      }
    }

    if (evidence.length > 0) {
      console.log('  Evidence-bearing runs:');
      for (const r of evidence.slice(0, 10)) {
        console.log(`  - ${r.testKey}: ${r.evidenceCount} file(s)`);
      }
    }
  }

  const reportPath = writeReport(allRows);
  console.log(`\nReport: ${reportPath}\n`);
}

main().catch((err) => {
  console.error(`\n💥 ${err.message}`);
  process.exit(1);
});
